---
- name: Teekkariravintolat
  address: Otakaari 24, Espoo
  campus: Otaniemi
  open: Mon-Fri 10:30-15:00
  url:
    fi: http://www.sodexo.fi/dipoli
  location:
    lat: 60.1847778
    lng: 24.8309887

- name: TUAS-talo
  address: Otaniementie 17, Espoo
  campus: Otaniemi
  open: Mon-Fri 10:30-14:00
  url:
    fi: http://www.amica.fi/api/restaurant/menu/week?language=fi&restaurantPageId=9291&weekDate=
    en: http://www.amica.fi/api/restaurant/menu/week?language=en&restaurantPageId=9291&weekDate=
  location:
    lat: 60.1868196
    lng: 24.8187598

- name: Alvari
  address: Otakaari 2, Espoo
  campus: Otaniemi
  open: Mon-Thu 10:30-17:00, Fri 10:30-15:00
  url:
    fi: http://www.amica.fi/api/restaurant/menu/week?language=fi&restaurantPageId=9271&weekDate=
    en: http://www.amica.fi/api/restaurant/menu/week?language=en&restaurantPageId=9271&weekDate=
  location:
    lat: 60.1862055
    lng: 24.8262297

- name: Elissa
  address: Otakaari 2, Espoo
  campus: Otaniemi
  open: Mon-Fri 08:00-14:00
  url:
    fi: http://www.amica.fi/elissa
  location:
    lat: 60.1862055
    lng: 24.8262297

- name: Puu
  address: Tekniikantie 3, Espoo
  campus: Otaniemi
  open: Mon-Fri 10:30-13:30
  url:
    fi: http://www.amica.fi/Puu2
  location:
    lat: 60.1805857
    lng: 24.8249123

- name: Täffä
  address: Otakaari 22, Espoo
  campus: Otaniemi
  open: Mon-Thu 10:30-16:00, Fri 10:30-15:00
  url:
    fi: https://www.teknologforeningen.fi/index.php?option=com_content&view=article&id=277&Itemid=128&lang=fi
    en: https://www.teknologforeningen.fi/index.php?option=com_content&view=article&id=277&Itemid=128&lang=en
  location:
    lat: 60.1858857
    lng: 24.83245

- name: Kvarkki
  address: Otakaari 3, Espoo
  campus: Otaniemi
  open: Mon-Fri 10:30-15:00
  url:
    fi: http://www.amica.fi/api/restaurant/menu/week?language=fi&restaurantPageId=9301&weekDate=
    en: http://www.amica.fi/api/restaurant/menu/week?language=en&restaurantPageId=9301&weekDate=
  location:
    lat: 60.1883476
    lng: 24.8294072

- name: Silinteri
  address: Otakaari 1 D, Espoo
  campus: Otaniemi
  open: Mon-Fri 11:40-13:00
  url:
    fi: http://www.amica.fi/silinteri
  location:
    lat: 60.1869326
    lng: 24.8272611

- name: Cantina
  address: Otakaari 24, Espoo
  campus: Otaniemi
  open: Mon-Thu 11:00-22:30, Fri 11:00-22:30, Sat 11:00-17:00
  url:
    fi: http://www.sodexo.fi/cantina
  location:
    lat: 60.1847778
    lng: 24.8309887

- name: Laurea Otaniemi
  address: Metsänpojankuja 3, Espoo
  campus: Otaniemi
  open: Mon-Thu 11:00-13:15, Fri 11:00-13:00
  url:
    fi: http://www.amica.fi/laureaotaniemi
  location:
    lat: 60.1858113
    lng: 24.8054439

- name: Rafla
  address: Runeberginkatu 14, Helsinki
  campus: Töölö
  open: Mon-Fri 10:30-16:15
  url:
    fi: http://www.amica.fi/api/restaurant/menu/week?language=fi&restaurantPageId=8059&weekDate=
    en: http://www.amica.fi/api/restaurant/menu/week?language=en&restaurantPageId=8059&weekDate=
  location:
    lat: 60.17090660
    lng: 24.92364680

- name: Chydenia
  address: Runeberginkatu 22, Helsinki
  campus: Töölö
  open: Mon-Thu 11:00-14:30, Fri 11:00-14:00
  url:
    fi: http://www.amica.fi/api/restaurant/menu/week?language=fi&restaurantPageId=5794&weekDate=
    en: http://www.amica.fi/api/restaurant/menu/week?language=en&restaurantPageId=5794&weekDate=
  location:
    lat: 60.1735677
    lng: 24.9222099

- name: Hanken
  address: Arkadiankatu 22, Helsinki
  campus: Töölö
  open: Mon-Fri 11:00-15:00
  url:
    fi: http://www.amica.fi/api/restaurant/menu/week?language=fi&restaurantPageId=6170&weekDate=
    en: http://www.amica.fi/api/restaurant/menu/week?language=en&restaurantPageId=6170&weekDate=
  location:
    lat: 60.1712571
    lng: 24.9243845

- name: Sibelius-Akatemia / Café da Capo
  address: Pohjoinen Rautatiekatu 9, Helsinki
  campus: Töölö
  open: Mon-Thu 10:30-15:00, Fri 10:30-14:30
  url:
    fi: http://www.amica.fi/Ravintolat/Amica-ravintolat/Ravintolat-kaupungeittain/Helsinki/Sibelius-Akatemia-Cafe-da-Capo/
    en: http://www.amica.fi/en/Ravintolat/Amica-restaurants/Areas/Helsinki/The-Sibelius-Academy--Cafe-da-Capo-/
  location:
    lat: 60.1715396
    lng: 24.9325754

- name: Cafe da Capo
  address: Töölönkatu 28, Helsinki
  campus: Töölö
  open: Mon-Thu 10:30-16:00, Fri 10:30-15:00
  url:
    fi: http://www.amica.fi/cafedacapo
    en: http://www.amica.fi/en/cafedacapo
  location:
    lat: 60.1785198
    lng: 24.9266378

- name: HYSn Osakuntabaari
  address: Urho Kekkosen katu 4-6 D, Helsinki
  campus: Töölö
  open: Mon-Thu 11:00-15:30, Fri 11:00-15:00
  url:
    fi: http://www.hys.net/opiskelijapalvelut/osakuntabaari/ruokalista
  location:
    lat: 60.1687878
    lng: 24.9343696

- name: Musiikkitalon Ravintola
  address: Mannerheimintie 13 A, Helsinki
  campus: Töölö
  open: Mon-Fri 11:00-15:00
  url:
    fi: http://www.tapahtumaravintolat.fi/musiikkitalo/Ravintolapalvelut/fi_FI/Ravintola/
  location:
    lat: 60.1731905
    lng: 24.9344303

- name: Kipsari
  address: Hämeentie 135 E, Helsinki
  campus: Arabia
  open: Mon-Fri 08:00-19:00
  url:
    fi: https://www.facebook.com/kipsari
  location:
    lat: 60.2087625
    lng: 24.9756101

- name: Meccala
  address: Hämeentie 135 C, Helsinki
  campus: Arabia
  open: Mon-Thu 10:30-14:15, Fri 10:30-14:00
  url:
    fi: http://www.amica.fi/api/restaurant/menu/week?language=fi&restaurantPageId=7693&weekDate=
    en: http://www.amica.fi/api/restaurant/menu/week?language=en&restaurantPageId=6170&weekDate=
  location:
    lat: 60.2087625
    lng: 24.9756101

- name: Ravintola Arabianranta
  address: Hämeentie 135 A, Helsinki
  campus: Arabia
  open: Mon-Fri 10:30-13:30
  url:
    fi: http://www.compass-group.fi/ravintolat/Helsinki/ravintola-arabianranta/Lounaslista/
  location:
    lat: 60.20876250
    lng: 24.97561010

- name: Unicafe Chemicum
  address: A.I. Virtasen aukio 1, Helsinki
  campus: Kumpula
  open: Mon-Thu 10:30-15:30, Fri 10:30-15:00
  url:
    fi: http://www.hyyravintolat.fi/rss/fin/10/
    en: http://www.hyyravintolat.fi/rss/eng/10/
  location:
    lat: 60.2060455
    lng: 24.9634222

- name: Unicafe Exactum
  address: Gustaf Hällströmin katu 2 B, Helsinki
  campus: Kumpula
  open: Mon-Fri 11:00-14:30
  url:
    fi: http://www.hyyravintolat.fi/rss/fin/11/
    en: http://www.hyyravintolat.fi/rss/eng/11/
  location:
    lat: 60.2049747
    lng: 24.9634712

- name: Unicafe Metsätalo
  address: Fabianinkatu 39, Helsinki
  campus: Keskusta
  open: Mon-Thu 10:30-16:00, Fri 10:30-15:00
  url:
    fi: http://www.hyyravintolat.fi/rss/fin/1/
    en: http://www.hyyravintolat.fi/rss/eng/1/
  location:
    lat: 60.1722975
    lng: 24.949109

- name: Unicafe Olivia
  address: Siltavuorenpenger 5 A, Helsinki
  campus: Keskusta
  open: Mon-Thu 10:30-16:00, Fri 10:30-15:30
  url:
    fi: http://www.hyyravintolat.fi/rss/fin/2/
    en: http://www.hyyravintolat.fi/rss/eng/2/
  location:
   lat: 60.17510350
   lng: 24.95338530

- name: Unicafe Porthania
  address: Yliopistonkatu 3, Helsinki
  campus: Keskusta
  open: Mon-Thu 10:30-16:30, Fri 10:30-16:00
  url:
    fi: http://www.hyyravintolat.fi/rss/fin/3/
    en: http://www.hyyravintolat.fi/rss/eng/3/
  location:
   lat: 60.16995360
   lng: 24.94843540

- name: Unicafe Päärakennus
  address: Fabianinkatu 33, Helsinki
  campus: Keskusta
  open: Mon-Fri 10:30-16:30
  url:
    fi: http://www.hyyravintolat.fi/rss/fin/4/
    en: http://www.hyyravintolat.fi/rss/eng/4/
  location:
   lat: 60.16944179999999
   lng: 24.94945750

- name: Unicafe Rotunda
  address: Unioninkatu 36, Helsinki
  campus: Keskusta
  open: Mon-Fri 11:00-13:30
  url:
    fi: http://www.hyyravintolat.fi/rss/fin/5/
    en: http://www.hyyravintolat.fi/rss/eng/5/
  location:
   lat: 60.1703510
   lng: 24.95068510 

- name: Unicafe Soc&Kom
  address: Yrjö-Koskisen katu 3, Helsinki
  campus: Keskusta
  open: Mon-Fri 11:00-14:30
  url:
    fi: http://www.hyyravintolat.fi/rss/fin/15/
    en: http://www.hyyravintolat.fi/rss/eng/15/
  location:
   lat: 60.17308030
   lng: 24.95251190

- name: Unicafe Topelias
  address: Unioninkatu 38, Helsinki
  campus: Keskusta
  open: Mon-Thu 11:00-14:30, Fri 11:00-14:00
  url:
    fi: http://www.hyyravintolat.fi/rss/fin/6/
    en: http://www.hyyravintolat.fi/rss/eng/6/
  location:
   lat: 60.17186450000001
   lng: 24.95048410

- name: Unicafe Valtiotiede
  address: Unioninkatu 37, Helsinki
  campus: Keskusta
  open: Mon-Fri 11:00-14:00
  url:
    fi: http://www.hyyravintolat.fi/rss/fin/7/
    en: http://www.hyyravintolat.fi/rss/eng/7/
  location:
    lat: 60.173379
    lng: 24.9506235

- name: Unicafe Ylioppilasaukio
  address: Mannerheimintie 3 B, Helsinki
  campus: Keskusta
  open: Mon-Fri 11:00-19:00, Sat 11:00-18:00
  url:
    fi: http://www.hyyravintolat.fi/rss/fin/8/
    en: http://www.hyyravintolat.fi/rss/eng/8/
  location:
    lat: 60.1693166
    lng: 24.9408102

- name: Unicafe Kookos
  address: Haapaniemenkatu 6, Helsinki
  campus: Kallio
  open: Mon-Thu 11:00-17:00, Fri 11:00-15:00
  url:
    fi: http://www.hyyravintolat.fi/rss/fin/16/
    en: http://www.hyyravintolat.fi/rss/eng/16/
  location:
    lat: 60.1811256
    lng: 24.9587522

- name: Unicafe Biokeskus
  address: Viikinkaari 9, Helsinki
  campus: Viikki
  open: Mon-Fri 10:30-15:00
  url:
    fi: http://www.hyyravintolat.fi/rss/fin/18/
    en: http://www.hyyravintolat.fi/rss/eng/18/
  location:
    lat: 60.2269484
    lng: 25.0139846

- name: Unicafe Korona
  address: Viikinkaari 11, Helsinki
  campus: Viikki
  open: Mon-Fri 11:00-14:00
  url:
    fi: http://www.hyyravintolat.fi/rss/fin/19/
    en: http://www.hyyravintolat.fi/rss/eng/19/
  location:
    lat: 60.2271911
    lng: 25.0123344

- name: Unicafe Viikuna
  address: Agnes Sjöbergin katu 2, Helsinki
  campus: Viikki
  open: Mon-Fri 10:30-14:30
  url:
    fi: http://www.hyyravintolat.fi/rss/fin/21/
    en: http://www.hyyravintolat.fi/rss/eng/21/
  location:
    lat: 60.229297
    lng: 25.0218129

- name: Tähkä
  address: Koetilantie 7, Helsinki
  campus: Viikki
  open: Mon-Thu 10:30-13:30, Fri 10:30-13:00
  url:
    fi: http://www.amica.fi/api/restaurant/menu/week?language=en&restaurantPageId=6340&weekDate=
  location:
    lat: 60.2230593
    lng: 25.0206768

- name: Ladonlukko
  address: Latokartanonkaari 9 A, Helsinki
  campus: Viikki
  open: Mon-Fri 10:30-14:30
  url:
    fi: http://www.sodexo.fi/ravintolaladonlukko
  location:
    lat: 60.2290679
    lng: 25.0185889

####### Lisätyt 24.4.2014
- name: Arcada
  address:
  campus: Kallio / Vallila
  open: Mon-Thu 10:45-15:15, Fri 10:45-14:30
  url:
    fi: http://www.amica.fi/api/restaurant/menu/week?language=fi&restaurantPageId=7734&weekDate=
  location:
    lat:
    lng:

- name: Diakonia
  address:
  campus: Kallio / Vallila
  open: Mon-Fri 10:45-13:00
  url:
    fi: http://www.amica.fi/Ravintolat/Amica-ravintolat/Ravintolat-kaupungeittain/Helsinki/Diakonia-Ammattikorkeakoulu/
  location:
    lat:
    lng:

- name: Helia-Bistro
  address:
  campus: Pasila
  open: Mon-Fri 10:30-14:00
  url:
    fi: http://www.amica.fi/api/restaurant/menu/week?language=fi&restaurantPageId=6143&weekDate=
  location:
    lat:
    lng:

- name: Alppica
  address:
  campus: Kallio / Vallila
  open: Mon-Fri 10:30-13:30
  url:
    fi: http://www.amica.fi/Ravintolat/Amica-ravintolat/Ravintolat-kaupungeittain/Helsinki/Helsingin-Diakonissalaitos--Alppica/
  location:
    lat:
    lng:

- name: Tähkä
  address:
  campus: Töölö
  open: Mon-Fri 10:30-13:00
  url:
    fi: http://www.amica.fi/api/restaurant/menu/week?language=fi&restaurantPageId=6340&weekDate=
  location:
    lat:
    lng:

- name: Pääraide Opetustalo
  address:
  campus: Pasila
  open: Mon-Thu 10:15-16:00, Fri 10:15-14:30
  url:
    fi: http://www.amica.fi/api/restaurant/menu/week?language=fi&restaurantPageId=7041&weekDate=
  location:
    lat:
    lng:

- name: Jamipaja
  address:
  campus: Arabia
  open: Mon-Fri 11:00-14:30
  url:
    fi: http://www.amica.fi/Ravintolat/Amica-ravintolat/Ravintolat-kaupungeittain/Helsinki/Pop-Jazz-Konservatorio--Jamipaja/
  location:
    lat:
    lng:

- name: Teak
  address:
  campus: Kallio / Vallila
  open: Mon-Thu 11:00-17:00, Fri 11:00-16:00
  url:
    fi: http://www.amica.fi/api/restaurant/menu/week?language=fi&restaurantPageId=5457&weekDate=
  location:
    lat:
    lng:

- name: Mäkelän Koulu
  address:
  campus: Kallio / Vallila
  open: Mon-Fri 10:30-14:00
  url:
    fi: http://www.sodexo.fi/hbc
  location:
    lat:
    lng:

- name: Unicafe Meilahti
  address:
  campus: Meilahti
  open: Mon-Thu 10:30-14:30, Fri 10:30-14:00
  url:
    en: http://www.hyyravintolat.fi/en/unicafe#/Meilahti/Meilahti/4/13
    fi: http://www.hyyravintolat.fi/unicafe#/Meilahti/Meilahti/4/13
  location:
    lat:
    lng:

- name: Unicafe Ruskeasuo
  address:
  campus: Ruskeasuo
  open: Mon-Thu 10:30-14:30, Fri 10:30-14:00
  url:
    en: http://www.hyyravintolat.fi/en/unicafe#/Ruskeasuo/Ruskeasuo/8/14
    fi: http://www.hyyravintolat.fi/unicafe#/Ruskeasuo/Ruskeasuo/8/14
  location:
    lat:
    lng:

- name: Ravintola Serpens Yths
  address:
  campus: Töölö
  open:  Mon-Fri 10:30-19:00
  url:
    en: http://www.hyyravintolat.fi/en/unicafe#/YTHS/Ravintola20%Serpens/10/42
    fi: http://www.hyyravintolat.fi/unicafe#/YTHS/Ravintola%20Serpens/10/42
  location:
    lat:
    lng:

- name: Metropolia Bulevardi
  address:
  campus: Keskusta
  open: Mon-Fri 10:30-14:30
  url:
    en: http://www.hyyravintolat.fi/en/unicafe#/Metropolia/Bulevardi/9/28
    fi: http://www.hyyravintolat.fi/unicafe#/Metropolia/Bulevardi/9/28
  location:
    lat:
    lng:

- name: Metropolia Hämeentie
  address:
  campus: Kallio / Vallila
  open:  Mon-Fri 10:30-14:30
  url:
    en: http://www.hyyravintolat.fi/en/unicafe#/Metropolia/Hameentie/9/33
    fi: http://www.hyyravintolat.fi/unicafe#/Metropolia/Hameentie/9/33
  location:
    lat:
    lng:

- name: Metropolia Sofianlehto
  address:
  campus: Kumpula
  open:  Mon-Fri 10:30-15:30
  url:
    en: http://www.hyyravintolat.fi/en/unicafe#/Metropolia/Sofianlehto/9/34
    fi: http://www.hyyravintolat.fi/unicafe#/Metropolia/Sofianlehto/9/34
  location:
    lat:
    lng:

- name: Metropolia Tukholmankatu
  address:
  campus: Meilahti
  open:  Mon-Thu 10:30-14:30, Fri 10:30-14:00
  url:
    en: http://www.hyyravintolat.fi/en/unicafe#/Metropolia/Tukholmankatu/9/31
    fi: http://www.hyyravintolat.fi/unicafe#/Metropolia/Tukholmankatu/9/31
  location:
    lat:
    lng: